"""create repository_analysis table

Revision ID: 35b5a8404d55
Revises: 
Create Date: 2026-09-27 08:11:43.506127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35b5a8404d55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_full_name', sa.String(), nullable=False),
    sa.Column('repo_url', sa.String(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=False),
    sa.Column('default_branch', sa.String(), nullable=True),
    sa.Column('analysis_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_full_name', 'commit_sha', name='uq_repo_commit')
    )
    op.create_index(op.f('ix_repository_analysis_repo_full_name'), 'repository_analysis', ['repo_full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repository_analysis_repo_full_name'), table_name='repository_analysis')
    op.drop_table('repository_analysis')
    # ### end Alembic commands ###
